<?php

namespace LaunchPoint\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use LaunchPoint\Traits\CanDisplayLogo;

/**
 * Class MakeRequestCommand
 *
 * Artisan command to generate a FormRequest class.
 * Produces authorize(), rules(), messages(), and attributes() out of the box.
 *
 * Usage:
 *   php artisan launchpoint:make-request StoreProductRequest
 *   php artisan launchpoint:make-request StoreProductRequest --model=Product
 */
class MakeRequestCommand extends Command
{
    use CanDisplayLogo;

    /**
     * @var string
     */
    protected $signature = 'launchpoint:make-request
                            {name   : The name of the request class (e.g. StoreProductRequest)}
                            {--model= : Optionally hint the model name in the docblock}';

    /**
     * @var string
     */
    protected $description = 'Create a new FormRequest class with authorize(), rules(), messages(), and attributes()';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        $name  = Str::studly($this->argument('name'));
        $model = $this->option('model') ? Str::studly($this->option('model')) : null;

        // Ensure name ends with "Request"
        if (!Str::endsWith($name, 'Request')) {
            $name .= 'Request';
        }

        $path = app_path("Http/Requests/{$name}.php");

        if (File::exists($path)) {
            $this->error("Request [{$name}] already exists.");
            return self::FAILURE;
        }

        File::ensureDirectoryExists(app_path('Http/Requests'));
        File::put($path, $this->requestStub($name, $model));
        $this->components->info("Request [{$name}] created → app/Http/Requests/{$name}.php");

        return self::SUCCESS;
    }

    /**
     * Generate the FormRequest stub.
     *
     * @param string      $class
     * @param string|null $model
     * @return string
     */
    protected function requestStub(string $class, ?string $model): string
    {
        $modelHint = $model
            ? " * Validates input data for the [{$model}] model.\n *"
            : '';

        return <<<PHP
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;

/**
 * Class {$class}
 *{$modelHint}
 * FormRequest generated by LaunchPoint.
 */
class {$class} extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            //
        ];
    }

    /**
     * Get custom validation error messages.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            //
        ];
    }

    /**
     * Get custom attribute names for error messages.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return [
            //
        ];
    }

    /**
     * Handle a failed validation attempt.
     * Returns a structured JSON response instead of a redirect.
     *
     * @param Validator \$validator
     * @throws HttpResponseException
     */
    protected function failedValidation(Validator \$validator): void
    {
        throw new HttpResponseException(
            response()->json([
                'code'    => 422,
                'message' => 'Validation failed.',
                'errors'  => \$validator->errors(),
            ], 422)
        );
    }
}
PHP;
    }
}
