<?php

namespace LaunchPoint\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use LaunchPoint\Traits\CanDisplayLogo;

/**
 * Class MakeResourceCommand
 *
 * Artisan command to generate an API Resource class.
 * Optionally generates a ResourceCollection alongside.
 *
 * Usage:
 *   php artisan launchpoint:make-resource ProductResource
 *   php artisan launchpoint:make-resource Product --collection
 */
class MakeResourceCommand extends Command
{
    use CanDisplayLogo;

    /**
     * @var string
     */
    protected $signature = 'launchpoint:make-resource
                            {name        : The name of the resource (e.g. Product or ProductResource)}
                            {--collection : Also generate a ResourceCollection class}';

    /**
     * @var string
     */
    protected $description = 'Create an API Resource class (use --collection to also generate a ResourceCollection)';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        $rawName    = Str::studly($this->argument('name'));
        $collection = $this->option('collection');

        // Normalize: strip "Resource" suffix to get base name
        $base = Str::endsWith($rawName, 'Resource')
            ? Str::replaceLast('Resource', '', $rawName)
            : $rawName;

        $resourceClass    = $base . 'Resource';
        $collectionClass  = $base . 'ResourceCollection';

        // --- Resource ---
        $resourcePath = app_path("Http/Resources/{$resourceClass}.php");

        if (File::exists($resourcePath)) {
            $this->error("Resource [{$resourceClass}] already exists.");
            return self::FAILURE;
        }

        File::ensureDirectoryExists(app_path('Http/Resources'));
        File::put($resourcePath, $this->resourceStub($resourceClass, $base));
        $this->components->info("Resource [{$resourceClass}] created → app/Http/Resources/{$resourceClass}.php");

        // --- ResourceCollection (optional) ---
        if ($collection) {
            $collectionPath = app_path("Http/Resources/{$collectionClass}.php");

            if (File::exists($collectionPath)) {
                $this->warn("ResourceCollection [{$collectionClass}] already exists. Skipping.");
            } else {
                File::put($collectionPath, $this->collectionStub($collectionClass, $resourceClass, $base));
                $this->components->info("ResourceCollection [{$collectionClass}] created → app/Http/Resources/{$collectionClass}.php");
            }
        }

        return self::SUCCESS;
    }

    /**
     * Generate the JsonResource stub.
     *
     * @param string $class
     * @param string $model
     * @return string
     */
    protected function resourceStub(string $class, string $model): string
    {
        return <<<PHP
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * Class {$class}
 *
 * API Resource for the [{$model}] model.
 * Generated by LaunchPoint.
 *
 * @mixin \App\Models\\{$model}
 */
class {$class} extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request \$request
     * @return array<string, mixed>
     */
    public function toArray(Request \$request): array
    {
        return [
            'id'         => \$this->id,
            'created_at' => \$this->created_at?->toDateTimeString(),
            'updated_at' => \$this->updated_at?->toDateTimeString(),
        ];
    }
}
PHP;
    }

    /**
     * Generate the ResourceCollection stub.
     *
     * @param string $class
     * @param string $resourceClass
     * @param string $model
     * @return string
     */
    protected function collectionStub(string $class, string $resourceClass, string $model): string
    {
        return <<<PHP
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;

/**
 * Class {$class}
 *
 * ResourceCollection for [{$model}] — wraps a collection of {$resourceClass}.
 * Generated by LaunchPoint.
 */
class {$class} extends ResourceCollection
{
    /**
     * The resource that this resource collects.
     *
     * @var string
     */
    public \$collects = {$resourceClass}::class;

    /**
     * Transform the resource collection into an array.
     *
     * @param Request \$request
     * @return array<string, mixed>
     */
    public function toArray(Request \$request): array
    {
        return [
            'data' => \$this->collection,
        ];
    }

    /**
     * Get additional data that should be returned with the resource array.
     *
     * @param Request \$request
     * @return array<string, mixed>
     */
    public function with(Request \$request): array
    {
        return [
            'meta' => [
                'total' => \$this->collection->count(),
            ],
        ];
    }
}
PHP;
    }
}
