<?php

namespace LaunchPoint\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use LaunchPoint\Traits\CanDisplayLogo;

/**
 * Class MakeModelCommand
 *
 * Artisan command to generate an Eloquent Model class.
 * Optionally creates a migration, factory, and seeder.
 *
 * Usage:
 *   php artisan launchpoint:make-model Product
 *   php artisan launchpoint:make-model Product --migration
 *   php artisan launchpoint:make-model Product --all
 */
class MakeModelCommand extends Command
{
    use CanDisplayLogo;

    /**
     * @var string
     */
    protected $signature = 'launchpoint:make-model
                            {name : The name of the model (e.g. Product)}
                            {--migration : Create a migration file for the model}
                            {--factory   : Create a factory for the model}
                            {--seeder    : Create a seeder for the model}
                            {--all       : Create migration, factory, and seeder}';

    /**
     * @var string
     */
    protected $description = 'Create a new Eloquent model (use --all to also generate migration, factory & seeder)';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        $name      = Str::studly($this->argument('name'));
        $all       = $this->option('all');
        $migration = $this->option('migration') || $all;
        $factory   = $this->option('factory')   || $all;
        $seeder    = $this->option('seeder')     || $all;

        $path = app_path("Models/{$name}.php");

        if (File::exists($path)) {
            $this->error("Model [{$name}] already exists.");
            return self::FAILURE;
        }

        File::ensureDirectoryExists(app_path('Models'));
        File::put($path, $this->modelStub($name));
        $this->components->info("Model [{$name}] created → app/Models/{$name}.php");

        if ($migration) {
            $table = Str::snake(Str::plural($name));
            $this->call('make:migration', ['name' => "create_{$table}_table"]);
        }

        if ($factory) {
            $this->call('make:factory', ['name' => "{$name}Factory", '--model' => $name]);
        }

        if ($seeder) {
            $this->call('make:seeder', ['name' => "{$name}Seeder"]);
        }

        return self::SUCCESS;
    }

    /**
     * Generate the model class stub.
     *
     * @param string $class
     * @return string
     */
    protected function modelStub(string $class): string
    {
        return <<<PHP
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class {$class}
 *
 * Eloquent model generated by LaunchPoint.
 *
 * @property int \$id
 * @property \Carbon\Carbon \$created_at
 * @property \Carbon\Carbon \$updated_at
 */
class {$class} extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<string>
     */
    protected \$fillable = [
        //
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected \$casts = [
        //
    ];
}
PHP;
    }
}
