<?php

namespace KhaledAbdalbasit\LaunchPoint\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class MakeRepositoryCommand extends Command
{
    protected $signature = 'launchpoint:make-repository {name} {--model=}';

    protected $description = 'Create a new repository class';

    public function handle()
    {
        $name = $this->argument('name');
        $model = $this->option('model');

        $path = app_path("Repositories/{$name}.php");

        if (File::exists($path)) {
            $this->error('Repository already exists.');
            return;
        }

        if (!File::exists(app_path('Repositories'))) {
            File::makeDirectory(app_path('Repositories'), 0755, true);
        }

        $stub = $model
            ? $this->modelStub($name, $model)
            : $this->basicStub($name);

        File::put($path, $stub);

        $this->info("Repository {$name} created successfully.");
    }

    protected function basicStub($class)
    {
        return <<<PHP
<?php

namespace App\Repositories;

/**
 * Class {$class}
 *
 * Base repository generated by LaunchPoint.
 */
class {$class}
{

}
PHP;
    }

    protected function modelStub($class, $model)
    {
        return <<<PHP
<?php

namespace App\Repositories;

use App\Models\\{$model};
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;

/**
 * Class {$class}
 *
 * Repository responsible for database operations related to {$model}.
 */
class {$class}
{
    /**
     * The model instance.
     *
     * @var {$model}
     */
    protected {$model} \$model;

    /**
     * {$class} constructor.
     *
     * @param {$model} \$model
     */
    public function __construct({$model} \$model)
    {
        \$this->model = \$model;
    }

    /**
     * Get all records.
     *
     * @return \\Illuminate\Database\Eloquent\Collection
     * @throws QueryException
     */
    public function all()
    {
        try {
            return \$this->model->all();
        } catch (QueryException \$e) {
            throw \$e;
        }
    }

    /**
     * Find record by ID or throw exception.
     *
     * @param int \$id
     * @return {$model}
     * @throws ModelNotFoundException
     */
    public function findOrFail(\$id)
    {
        \$model = \$this->model->find(\$id);

        if (!\$model) {
            throw new ModelNotFoundException("{$model} not found.");
        }

        return \$model;
    }

    /**
     * Create new record.
     *
     * @param array \$data
     * @return {$model}
     * @throws QueryException
     */
    public function create(array \$data)
    {
        try {
            return \$this->model->create(\$data);
        } catch (QueryException \$e) {
            throw \$e;
        }
    }

    /**
     * Update record by ID.
     *
     * @param int \$id
     * @param array \$data
     * @return {$model}
     * @throws ModelNotFoundException
     * @throws QueryException
     */
    public function update(\$id, array \$data)
    {
        \$model = \$this->findOrFail(\$id);

        try {
            \$model->update(\$data);
        } catch (QueryException \$e) {
            throw \$e;
        }

        return \$model;
    }

    /**
     * Delete record by ID.
     *
     * @param int \$id
     * @return bool|null
     * @throws ModelNotFoundException
     * @throws QueryException
     */
    public function delete(\$id)
    {
        \$model = \$this->findOrFail(\$id);

        try {
            return \$model->delete();
        } catch (QueryException \$e) {
            throw \$e;
        }
    }
}
PHP;
    }
}
