<?php

namespace LaunchPoint\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

use LaunchPoint\Traits\CanDisplayLogo;

/**
 * Class MakeServiceCommand
 *
 * Artisan command to generate a new Service class.
 * When --model is provided, automatically creates a matching Repository
 * and generates a Service that delegates all CRUD operations to it.
 *
 * Chain: Controller → Service → Repository → Model
 */
class MakeServiceCommand extends Command
{
    use CanDisplayLogo;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'launchpoint:make-service {name} {--model=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new service class (auto-creates matching Repository when --model is given)';

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        $this->displayLogo();
        
        $name  = $this->argument('name');
        $model = $this->option('model');

        // Determine the path for the service class
        $path = app_path("Services/{$name}.php");

        // Prevent overwriting an existing service
        if (File::exists($path)) {
            $this->error("Service [{$name}] already exists.");
            return;
        }

        // Ensure the Services directory exists
        if (!File::exists(app_path('Services'))) {
            File::makeDirectory(app_path('Services'), 0755, true);
        }

        if ($model) {
            // Derive repository name: e.g. UserService → UserRepository
            $repoName = $this->deriveRepositoryName($name);

            // Auto-create the repository if it doesn't exist
            $repoPath = app_path("Repositories/{$repoName}.php");
            if (!File::exists($repoPath)) {
                $this->call('launchpoint:make-repository', [
                    'name'    => $repoName,
                    '--model' => $model,
                ]);
                $this->info("Repository [{$repoName}] created for model [{$model}].");
            }

            $stub = $this->repositoryStub($name, $repoName);
        } else {
            $stub = $this->basicStub($name);
        }

        // Write the service class to disk
        File::put($path, $stub);

        $this->info("Service [{$name}] created successfully.");
    }

    /**
     * Derive the Repository class name from the Service name.
     * Examples:
     *   UserService   → UserRepository
     *   ProductService → ProductRepository
     *   Auth/AuthService → Auth/AuthRepository  (preserves sub-paths)
     *
     * @param string $serviceName
     * @return string
     */
    protected function deriveRepositoryName(string $serviceName): string
    {
        // Handle sub-directory paths like "Auth/AuthService"
        $base = basename(str_replace('\\', '/', $serviceName));
        $dir  = ltrim(str_replace(basename(str_replace('\\', '/', $serviceName)), '', str_replace('\\', '/', $serviceName)), '/\\');

        if (Str::endsWith($base, 'Service')) {
            $repoBase = Str::replaceLast('Service', 'Repository', $base);
        } else {
            $repoBase = $base . 'Repository';
        }

        return $dir ? $dir . '/' . $repoBase : $repoBase;
    }

    /**
     * Generate a basic service stub without any dependency.
     *
     * @param string $class
     * @return string
     */
    protected function basicStub($class)
    {
        return <<<PHP
<?php

namespace App\Services;

/**
 * Class {$class}
 *
 * Base service class generated by LaunchPoint.
 */
class {$class}
{

}
PHP;
    }

    /**
     * Generate a service stub that injects a Repository (Repository Pattern).
     * The Service delegates all CRUD operations to the Repository.
     *
     * @param string \$class      Service class name
     * @param string \$repoClass  Repository class name
     * @return string
     */
    protected function repositoryStub(string $class, string $repoClass)
    {
        return <<<PHP
<?php

namespace App\Services;

use App\Repositories\\{$repoClass};
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Exception;

/**
 * Class {$class}
 *
 * Service layer generated by LaunchPoint.
 * Delegates all data operations to {$repoClass}.
 *
 * Chain: Controller → {$class} → {$repoClass} → Model
 */
class {$class}
{
    /**
     * The injected repository instance.
     *
     * @var {$repoClass}
     */
    protected {$repoClass} \$repository;

    /**
     * {$class} constructor.
     *
     * @param {$repoClass} \$repository
     */
    public function __construct({$repoClass} \$repository)
    {
        \$this->repository = \$repository;
    }

    /**
     * Retrieve all records.
     *
     * @return Collection
     *
     * @throws QueryException
     */
    public function getAll(): Collection
    {
        return \$this->repository->all();
    }

    /**
     * Find a record by ID or throw ModelNotFoundException.
     *
     * @param int \$id
     * @return Model
     *
     * @throws ModelNotFoundException
     */
    public function findOrFail(int \$id): Model
    {
        return \$this->repository->findOrFail(\$id);
    }

    /**
     * Create a new record.
     *
     * @param array \$data
     * @return Model
     *
     * @throws QueryException
     */
    public function create(array \$data): Model
    {
        return \$this->repository->create(\$data);
    }

    /**
     * Update a record by ID.
     *
     * @param int   \$id
     * @param array \$data
     * @return Model
     *
     * @throws ModelNotFoundException
     * @throws QueryException
     */
    public function update(int \$id, array \$data): Model
    {
        return \$this->repository->update(\$id, \$data);
    }

    /**
     * Delete a record by ID.
     *
     * @param int \$id
     * @return bool|null
     *
     * @throws ModelNotFoundException
     * @throws QueryException
     */
    public function delete(int \$id): bool|null
    {
        return \$this->repository->delete(\$id);
    }
}
PHP;
    }
}
