<?php

namespace KhaledAbdalbasit\LaunchPoint\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Class MakeServiceCommand
 *
 * Artisan command to generate a new Service class.
 * Supports optional model injection for standard CRUD operations.
 */
class MakeServiceCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'launchpoint:make-service {name} {--model=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new service class with optional model injection';

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        $name = $this->argument('name');
        $model = $this->option('model');

        // Determine the path for the service class
        $path = app_path("Services/{$name}.php");

        // Prevent overwriting an existing service
        if (File::exists($path)) {
            $this->error("Service {$name} already exists.");
            return;
        }

        // Ensure the Services directory exists
        if (!File::exists(app_path('Services'))) {
            File::makeDirectory(app_path('Services'), 0755, true);
        }

        // Choose the stub based on whether a model is provided
        $stub = $model ? $this->modelStub($name, $model) : $this->basicStub($name);

        // Write the service class to disk
        File::put($path, $stub);

        $this->info("Service {$name} created successfully.");
    }

    /**
     * Generate a basic service stub without a model.
     *
     * @param string $class
     * @return string
     */
    protected function basicStub($class)
    {
        return <<<PHP
<?php

namespace App\Services;

/**
 * Class {$class}
 *
 * Base service class generated by LaunchPoint.
 */
class {$class}
{

}
PHP;
    }

    /**
     * Generate a service stub connected to a model with CRUD methods.
     *
     * @param string \$class
     * @param string \$model
     * @return string
     */
    protected function modelStub($class, $model)
    {
        return <<<PHP
<?php

namespace App\Services;

use App\Models\\{$model};
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Exception;

/**
 * Class {$class}
 *
 * Service layer responsible for handling business logic for {$model}.
 */
class {$class}
{
    /**
     * The model instance.
     *
     * @var {$model}
     */
    protected {$model} \$model;

    /**
     * {$class} constructor.
     *
     * @param {$model} \$model
     */
    public function __construct({$model} \$model)
    {
        \$this->model = \$model;
    }

    /**
     * Retrieve all records.
     *
     * @return \\Illuminate\Database\Eloquent\Collection
     *
     * @throws QueryException
     */
    public function getAll()
    {
        try {
            return \$this->model->all();
        } catch (QueryException \$e) {
            throw \$e;
        }
    }

    /**
     * Find a record by ID or throw ModelNotFoundException.
     *
     * @param int \$id
     * @return {$model}
     *
     * @throws ModelNotFoundException
     */
    public function findOrFail(\$id)
    {
        \$model = \$this->model->find(\$id);

        if (!\$model) {
            throw new ModelNotFoundException("{$model} not found.");
        }

        return \$model;
    }

    /**
     * Create a new record.
     *
     * @param array \$data
     * @return {$model}
     *
     * @throws QueryException
     */
    public function create(array \$data)
    {
        try {
            return \$this->model->create(\$data);
        } catch (QueryException \$e) {
            throw \$e;
        }
    }

    /**
     * Update a record by ID.
     *
     * @param int \$id
     * @param array \$data
     * @return {$model}
     *
     * @throws ModelNotFoundException
     * @throws QueryException
     */
    public function update(\$id, array \$data)
    {
        \$model = \$this->findOrFail(\$id);

        try {
            \$model->update(\$data);
        } catch (QueryException \$e) {
            throw \$e;
        }

        return \$model;
    }

    /**
     * Delete a record by ID.
     *
     * @param int \$id
     * @return bool|null
     *
     * @throws ModelNotFoundException
     * @throws QueryException
     */
    public function delete(\$id)
    {
        \$model = \$this->findOrFail(\$id);

        try {
            return \$model->delete();
        } catch (QueryException \$e) {
            throw \$e;
        }
    }
}
PHP;
    }
}
